# network architecture
# encoder related
emotion_recognition: true
encoder: conformer
encoder_conf:
    output_size: 256   # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 1      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: true
    cnn_module_kernel: 15
    use_cnn_module: True
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'

decoder: transformer
decoder_conf:
  attention_heads: 4
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 4
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
# hybrid CTC/attention
model_conf:
    input_ln: False
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

dataset_conf:
    filter_conf:
        max_length: 30000
        min_length: 0
        token_max_length: 2000
        token_min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    feats_type: 'fbank'
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.1
    # mfcc_conf:
    #     num_mel_bins: 40
    #     frame_shift: 10
    #     frame_length: 25
    #     num_ceps: 40
    #     low_freq: 20
    #     high_freq: -400
    #     dither: 0.1
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: False
    # sort_conf:
    #     sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'static' # static or dynamic
        batch_size: 1

grad_clip: 4
accum_grad: 1
max_epoch: 100
log_interval: 100

# use 1 optimizer
optim: adam
optim_conf:
    lr: 0.0001
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 30000



